### ISSUE TITLE
Design database schema 

### ISSUE THREAD

**Issue by tierwixt** [great-lakes/project-superior-bot#2]

**Comment by howlowck** [comment]
![image](https://user-images.githubusercontent.com/338265/35180854-b982ebaa-fd7d-11e7-9206-3e08e759e9f8.png)

http://www.laravelsd.com/share/2ujJjf

**Comment by howlowck** [comment]
@KSLHacks @SarahSexton @tierwixt Please review the schema above.  Blue tables are data tables, and Green tables are pivot tables.  Foreign Keys are signified by `FK` next to the column names.  

Please let me know if I missed anything
