### ISSUE TITLE
Integrate Survey into bot

### ISSUE THREAD

**Issue by KSLHacks** [great-lakes/project-superior-bot#63]
### Expected Behavior
Allow users to take the survey through Hanna, i.e "I would like to take the survey", "Show survey", etc..

### Requirements
- Survey is dynamically created through API (eventually customizable through dashboard)
- Survey information is submitted to API on completion
- Hanna displays a completion image so booth can give swag

**Comment by KSLHacks** [comment]
Almost complete. Tasks left:
- Display completion image for easy identification of survey completed
- Integrate with API

**Comment by kevinleung23** [comment]
Completed in PR #65 

- Administering survey based on dynamic data
- Collecting user survey responses correctly
